import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  const AppLocalizations(this.locale);

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        const AppLocalizations(Locale('en'));
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'Pamoja Twalima',
      'drawer_profile': 'Profile',
      'drawer_settings': 'Settings',
      'drawer_help': 'Help & Support',
      'drawer_about': 'About',
      'drawer_dark_mode': 'Dark Mode',
      'drawer_logout': 'Logout',
      'theme_dark_enabled': 'Dark mode enabled.',
      'theme_light_enabled': 'Light mode enabled.',
      'theme_system_enabled': 'Theme follows device setting.',
      'profile_title': 'Profile & Settings',
      'preferences': 'Preferences',
      'data_sync': 'Data & Sync',
      'about_section': 'About',
      'language_english': 'Language: English',
      'language_swahili': 'Language: Kiswahili',
      'theme': 'Theme',
      'sync_now': 'Sync Now',
      'manage_offline': 'Manage Offline Content',
      'audit_trail': 'Audit Trail',
      'privacy_terms': 'Privacy & Terms',
      'about_app': 'About Pamoja Twalima',
      'home_today': 'Today',
      'home_farm_snapshot': 'Farm Snapshot',
      'home_financial': 'Financial Overview',
      'home_alerts': 'Critical Alerts',
      'home_quick_actions': 'Quick Actions',
      'critical_alerts': 'Critical Alerts',
      'no_critical_alerts': 'No Critical Alerts',
      'everything_good': 'Everything looks good right now',
      'low_stock_alert': 'Low Stock Alert',
      'pending_tasks_alert': 'Pending Tasks',
      'financial_summary': 'Financial Summary',
      'view_all': 'View All',
      'todays_sales': "Today's Sales",
      'this_month': 'This Month',
      'production_value_today': "Today's Production Value",
      'quick_add_record': 'Add Record',
      'quick_sell': 'Sell',
      'quick_purchase': 'Purchase',
      'quick_tasks': 'Tasks',
      'notifications': 'Notifications',
      'close': 'Close',
      'no_new_notifications': 'No new notifications',
      'all_modules_healthy': 'All farm modules are in a healthy state.',
      'farm_management': 'Farm Management',
      'farm_overview': 'Overview',
      'farm_crops': 'Crops',
      'farm_animals': 'Animals',
      'farm_tasks': 'Tasks',
      'inventory': 'Inventory',
      'syncing_from_server': 'Syncing from server...',
      'sync_failed': 'Sync failed',
      'local_version_kept': 'Local version kept. Sync queued.',
      'server_version_applied': 'Server version applied.',
      'synced_items_from_server': 'Synced items from server',
      'sales': 'Sales',
      'performance': 'Performance',
      'total_revenue': 'Total Revenue',
      'pending': 'Pending',
      'transactions': 'Transactions',
      'paid': 'Paid',
      'average_order_value': 'Average order value',
      'contacts': 'Contacts',
      'suppliers': 'Suppliers',
      'customers': 'Customers',
      'staff': 'Staff',
      'supplier': 'Supplier',
      'customer': 'Customer',
      'staff_member': 'Staff Member',
      'failed_to_load': 'Failed to load',
      'save_failed': 'Save failed',
      'delete_failed': 'Delete failed',
      'no_items_yet': 'No items yet',
      'unnamed': 'Unnamed',
      'add': 'Add',
      'edit': 'Edit',
      'name_required': 'Name is required',
      'name_field': 'Name *',
      'role': 'Role',
      'phone': 'Phone',
      'email': 'Email',
      'address': 'Address',
      'notes': 'Notes',
      'cancel': 'Cancel',
      'save': 'Save',
      'conflict_center': 'Conflict Center',
      'resolve_all_use_server': 'Resolve All: Use Server',
      'resolve_all_keep_local': 'Resolve All: Keep Local',
      'no_sync_conflicts': 'No sync conflicts found.',
      'use_server': 'Use Server',
      'keep_local': 'Keep Local',
      'applied_server_version': 'applied server version',
      'local_version_queued': 'local version queued',
      'task_assigned': 'Assigned',
      'task_completed': 'Completed',
      'task_overdue': 'Overdue',
      'task_pending': 'Pending',
      'task_breeding': 'Breeding',
      'task_feeding': 'Feeding',
      'task_production': 'Production',
      'task_harvest': 'Harvest',
      'task_low_stock': 'Low Stock',
      'no_date': 'No date',
      'today': 'Today',
      'tomorrow': 'Tomorrow',
      'yesterday': 'Yesterday',
      'in_days': 'In {days} days',
      'days_ago_short': '{days}d ago',
      'inventory_history': 'Inventory History',
      'total_restock_cost': 'Total Restock Cost',
      'low_stock_alerts': 'Low Stock Alerts',
      'monthly_usage': 'Monthly Usage',
      'restocks': 'Restocks',
      'usage': 'Usage',
      'alerts': 'Alerts',
      'weather_forecast': 'Weather Forecast',
      'unable_load_weather': 'Unable to load weather',
      'current_weather': 'Current Weather',
      'humidity': 'Humidity',
      'wind': 'Wind',
      'rain': 'Rain',
      'seven_day_forecast': '7-Day Forecast',
      'rain_percent': '{percent}% rain',
      'knowledge_base': 'Knowledge Base',
      'search_knowledge_hint': 'Search diseases, crops, or treatments...',
      'articles_found': '{count} Articles Found',
      'ask_expert': 'Ask an Expert',
      'knowledge_category_all': 'All',
      'knowledge_category_crops': 'Crops',
      'knowledge_category_livestock': 'Livestock',
      'knowledge_category_poultry': 'Poultry',
      'knowledge_category_vegetables': 'Vegetables',
      'knowledge_category_soil_health': 'Soil Health',
      'knowledge_category_storage': 'Storage',
      'no_audit_events': 'No audit events yet.',
      'welcome_back': 'Welcome Back',
      'login_manage_farm': 'Login to manage your farm',
      'email_label': 'Email',
      'password_label': 'Password',
      'login_cta': 'Login',
      'no_account_prompt': "Don't have an account? ",
      'create_account_cta': 'Create account',
      'please_enter_email': 'Please enter your email',
      'please_enter_valid_email': 'Please enter a valid email',
      'please_enter_password': 'Please enter your password',
      'register_create_account': 'Create Account',
      'register_join_subtitle': 'Join Pamoja Twalima to grow smarter',
      'full_name_label': 'Full Name',
      'please_enter_name': 'Please enter your name',
      'password_requirements_hint':
          'Min 12 chars, uppercase, lowercase, number, symbol',
      'please_enter_new_password': 'Please enter a password',
      'password_min_chars': 'Password must be at least 12 characters',
      'password_uppercase': 'Password must contain uppercase letter',
      'password_lowercase': 'Password must contain lowercase letter',
      'password_number': 'Password must contain a number',
      'password_special': 'Password must contain a special character',
      'confirm_password_label': 'Confirm Password',
      'passwords_do_not_match': 'Passwords do not match',
      'phone_optional': 'Phone (optional)',
      'farm_name_optional': 'Farm Name (optional)',
      'location_optional': 'Location (optional)',
      'already_have_account': 'Already have an account? ',
      'create_account_title': 'Create Account',
      'login_prompt_title': 'Welcome Back',
      'onboarding_skip': 'Skip',
      'onboarding_next': 'Next',
      'onboarding_get_started': 'Get Started',
      'onboarding_welcome_title': 'Welcome to Pamoja Twalima',
      'onboarding_welcome_desc':
          'Empowering Kenyan farmers to grow smarter, trade better, and thrive together.',
      'onboarding_manage_title': 'Manage Your Farm',
      'onboarding_manage_desc':
          'Track crops, livestock, and expenses easily in one app.',
      'onboarding_market_title': 'Market & Weather Insights',
      'onboarding_market_desc':
          'Access market prices, forecasts, and sell directly via M-Pesa.',
      'language_set_swahili': 'Language set to Kiswahili.',
      'language_set_english': 'Language set to English.',
      'sync_running': 'Running sync...',
      'sync_completed': 'Sync completed.',
      'sync_failed_short': 'Sync failed.',
      'offline_content_title': 'Offline Content',
      'offline_content_desc':
          'Offline records are managed automatically. Use "Sync Now" to push and refresh data.',
      'ok': 'OK',
      'about_app_desc':
          'Farm management for crops, animals, inventory, and sales.',
      'privacy_terms_title': 'Privacy & Terms',
      'privacy_terms_desc':
          'Use consented farm data only and keep device access secure. Full policy text should be linked before release.',
      'close_button': 'Close',
      'edit_profile_title': 'Edit Profile',
      'name_label': 'Name',
      'location_label': 'Location',
      'profile_updated': 'Profile updated',
      'profile_update_failed': 'Failed to update profile',
      'theme_system_default': 'System default',
      'theme_light': 'Light',
      'theme_dark': 'Dark',
      'theme_updated_to': 'Theme updated to {theme}.',
      'apply': 'Apply',
      'logged_out_successfully': 'Logged out successfully',
      'logout_failed': 'Logout failed: {message}',
      'logout_confirm_title': 'Logout',
      'logout_confirm_body': 'Are you sure you want to logout?',
      'profile_default_name': 'Farmer',
      'help_support_title': 'Help & Support',
      'help_email': 'Email: support@pamoja-twalima.app',
      'help_phone': 'Phone: +254 700 000 000',
      'help_response_time': 'Response time: within 24 hours',
      'version_label': 'Version {version}',
      'error_auth_invalid_credentials': 'Invalid credentials',
      'error_auth_login_failed': 'Login failed',
      'error_auth_invalid_email_password': 'Invalid email or password',
      'error_auth_too_many_attempts':
          'Too many login attempts. Please try again later.',
      'error_auth_invalid_registration': 'Invalid registration data',
      'error_auth_registration_failed': 'Registration failed',
      'error_profile_load': 'Failed to load profile',
      'error_profile_logout': 'Failed to logout',
      'error_weather_load': 'Failed to load weather',
      'error_knowledge_load_topics': 'Failed to load topics',
      'error_audit_load': 'Failed to load audit events',
      'error_marketplace_load': 'Failed to load products',
      'error_marketplace_add': 'Failed to add product',
      'error_marketplace_update': 'Failed to update product',
      'error_marketplace_delete': 'Failed to delete product',
    },
    'sw': {
      'app_name': 'Pamoja Twalima',
      'drawer_profile': 'Wasifu',
      'drawer_settings': 'Mipangilio',
      'drawer_help': 'Msaada',
      'drawer_about': 'Kuhusu',
      'drawer_dark_mode': 'Mandhari ya Giza',
      'drawer_logout': 'Toka',
      'theme_dark_enabled': 'Mandhari ya giza imewashwa.',
      'theme_light_enabled': 'Mandhari ya mwanga imewashwa.',
      'theme_system_enabled': 'Mandhari inafuata kifaa.',
      'profile_title': 'Wasifu na Mipangilio',
      'preferences': 'Mapendeleo',
      'data_sync': 'Data na Usawazishaji',
      'about_section': 'Kuhusu',
      'language_english': 'Lugha: Kiingereza',
      'language_swahili': 'Lugha: Kiswahili',
      'theme': 'Mandhari',
      'sync_now': 'Sawazisha Sasa',
      'manage_offline': 'Dhibiti Data Nje ya Mtandao',
      'audit_trail': 'Historia ya Mabadiliko',
      'privacy_terms': 'Faragha na Masharti',
      'about_app': 'Kuhusu Pamoja Twalima',
      'home_today': 'Leo',
      'home_farm_snapshot': 'Muhtasari wa Shamba',
      'home_financial': 'Muhtasari wa Fedha',
      'home_alerts': 'Tahadhari Muhimu',
      'home_quick_actions': 'Vitendo vya Haraka',
      'critical_alerts': 'Tahadhari Muhimu',
      'no_critical_alerts': 'Hakuna Tahadhari Muhimu',
      'everything_good': 'Kila kitu kiko sawa kwa sasa',
      'low_stock_alert': 'Tahadhari ya Hisa Chini',
      'pending_tasks_alert': 'Kazi Zinazosubiri',
      'financial_summary': 'Muhtasari wa Fedha',
      'view_all': 'Tazama Zote',
      'todays_sales': 'Mauzo ya Leo',
      'this_month': 'Mwezi Huu',
      'production_value_today': 'Thamani ya Uzalishaji wa Leo',
      'quick_add_record': 'Ongeza Rekodi',
      'quick_sell': 'Uza',
      'quick_purchase': 'Nunua',
      'quick_tasks': 'Kazi',
      'notifications': 'Arifa',
      'close': 'Funga',
      'no_new_notifications': 'Hakuna arifa mpya',
      'all_modules_healthy': 'Mifumo yote iko katika hali nzuri.',
      'farm_management': 'Usimamizi wa Shamba',
      'farm_overview': 'Muhtasari',
      'farm_crops': 'Mazao',
      'farm_animals': 'Wanyama',
      'farm_tasks': 'Kazi',
      'inventory': 'Hesabu',
      'syncing_from_server': 'Inasawazisha kutoka kwa seva...',
      'sync_failed': 'Usawazishaji umeshindikana',
      'local_version_kept':
          'Toleo la ndani limehifadhiwa. Usawazishaji umewekwa.',
      'server_version_applied': 'Toleo la seva limetumika.',
      'synced_items_from_server': 'Vipengee vimesawazishwa kutoka seva',
      'sales': 'Mauzo',
      'performance': 'Utendaji',
      'total_revenue': 'Mapato Yote',
      'pending': 'Inasubiri',
      'transactions': 'Miamala',
      'paid': 'Imelipwa',
      'average_order_value': 'Wastani wa thamani ya oda',
      'contacts': 'Mawasiliano',
      'suppliers': 'Wasambazaji',
      'customers': 'Wateja',
      'staff': 'Wafanyakazi',
      'supplier': 'Msambazaji',
      'customer': 'Mteja',
      'staff_member': 'Mfanyakazi',
      'failed_to_load': 'Imeshindwa kupakia',
      'save_failed': 'Kuhifadhi kumeshindikana',
      'delete_failed': 'Kufuta kumeshindikana',
      'no_items_yet': 'Hakuna vipengee bado',
      'unnamed': 'Bila jina',
      'add': 'Ongeza',
      'edit': 'Hariri',
      'name_required': 'Jina linahitajika',
      'name_field': 'Jina *',
      'role': 'Wajibu',
      'phone': 'Simu',
      'email': 'Barua pepe',
      'address': 'Anwani',
      'notes': 'Maelezo',
      'cancel': 'Ghairi',
      'save': 'Hifadhi',
      'conflict_center': 'Kituo cha Migongano',
      'resolve_all_use_server': 'Tatua Zote: Tumia Seva',
      'resolve_all_keep_local': 'Tatua Zote: Hifadhi ya Ndani',
      'no_sync_conflicts': 'Hakuna migongano ya usawazishaji.',
      'use_server': 'Tumia Seva',
      'keep_local': 'Hifadhi ya Ndani',
      'applied_server_version': 'toleo la seva limetumika',
      'local_version_queued': 'toleo la ndani limewekwa kusawazishwa',
      'task_assigned': 'Amepewa',
      'task_completed': 'Imekamilika',
      'task_overdue': 'Imechelewa',
      'task_pending': 'Inasubiri',
      'task_breeding': 'Uzazi',
      'task_feeding': 'Ulishaji',
      'task_production': 'Uzalishaji',
      'task_harvest': 'Mavuno',
      'task_low_stock': 'Hisa Chini',
      'no_date': 'Hakuna tarehe',
      'today': 'Leo',
      'tomorrow': 'Kesho',
      'yesterday': 'Jana',
      'in_days': 'Baada ya siku {days}',
      'days_ago_short': 'siku {days} zilizopita',
      'inventory_history': 'Historia ya Hesabu',
      'total_restock_cost': 'Jumla ya Gharama za Kujaza',
      'low_stock_alerts': 'Tahadhari za Hisa Chini',
      'monthly_usage': 'Matumizi ya Mwezi',
      'restocks': 'Ujazaji',
      'usage': 'Matumizi',
      'alerts': 'Tahadhari',
      'weather_forecast': 'Utabiri wa Hali ya Hewa',
      'unable_load_weather': 'Imeshindwa kupakia hali ya hewa',
      'current_weather': 'Hali ya Hewa ya Sasa',
      'humidity': 'Unyevu',
      'wind': 'Upepo',
      'rain': 'Mvua',
      'seven_day_forecast': 'Utabiri wa Siku 7',
      'rain_percent': '{percent}% mvua',
      'knowledge_base': 'Maktaba ya Maarifa',
      'search_knowledge_hint': 'Tafuta magonjwa, mazao, au matibabu...',
      'articles_found': 'Makala {count} zimepatikana',
      'ask_expert': 'Muulize Mtaalamu',
      'knowledge_category_all': 'Zote',
      'knowledge_category_crops': 'Mazao',
      'knowledge_category_livestock': 'Mifugo',
      'knowledge_category_poultry': 'Kuku',
      'knowledge_category_vegetables': 'Mboga',
      'knowledge_category_soil_health': 'Afya ya Udongo',
      'knowledge_category_storage': 'Uhifadhi',
      'no_audit_events': 'Hakuna matukio ya ukaguzi bado.',
      'welcome_back': 'Karibu Tena',
      'login_manage_farm': 'Ingia kusimamia shamba lako',
      'email_label': 'Barua pepe',
      'password_label': 'Nenosiri',
      'login_cta': 'Ingia',
      'no_account_prompt': 'Huna akaunti? ',
      'create_account_cta': 'Fungua akaunti',
      'please_enter_email': 'Tafadhali ingiza barua pepe yako',
      'please_enter_valid_email': 'Tafadhali ingiza barua pepe sahihi',
      'please_enter_password': 'Tafadhali ingiza nenosiri lako',
      'register_create_account': 'Fungua Akaunti',
      'register_join_subtitle': 'Jiunge na Pamoja Twalima ukue kwa ufanisi',
      'full_name_label': 'Jina Kamili',
      'please_enter_name': 'Tafadhali ingiza jina lako',
      'password_requirements_hint':
          'Angalau herufi 12, kubwa, ndogo, namba na alama',
      'please_enter_new_password': 'Tafadhali ingiza nenosiri',
      'password_min_chars': 'Nenosiri lazima liwe angalau herufi 12',
      'password_uppercase': 'Nenosiri lazima liwe na herufi kubwa',
      'password_lowercase': 'Nenosiri lazima liwe na herufi ndogo',
      'password_number': 'Nenosiri lazima liwe na namba',
      'password_special': 'Nenosiri lazima liwe na alama maalum',
      'confirm_password_label': 'Thibitisha Nenosiri',
      'passwords_do_not_match': 'Manenosiri hayafanani',
      'phone_optional': 'Simu (si lazima)',
      'farm_name_optional': 'Jina la Shamba (si lazima)',
      'location_optional': 'Mahali (si lazima)',
      'already_have_account': 'Una akaunti tayari? ',
      'create_account_title': 'Fungua Akaunti',
      'login_prompt_title': 'Karibu Tena',
      'onboarding_skip': 'Ruka',
      'onboarding_next': 'Ifuatayo',
      'onboarding_get_started': 'Anza Sasa',
      'onboarding_welcome_title': 'Karibu Pamoja Twalima',
      'onboarding_welcome_desc':
          'Kuwawezesha wakulima wa Kenya kulima kwa ufanisi na kufanya biashara bora.',
      'onboarding_manage_title': 'Simamia Shamba Lako',
      'onboarding_manage_desc':
          'Fuatilia mazao, mifugo, na gharama kwa urahisi kwenye app moja.',
      'onboarding_market_title': 'Taarifa za Soko na Hali ya Hewa',
      'onboarding_market_desc':
          'Pata bei za soko, utabiri, na uza moja kwa moja kupitia M-Pesa.',
      'language_set_swahili': 'Lugha imewekwa kuwa Kiswahili.',
      'language_set_english': 'Lugha imewekwa kuwa Kiingereza.',
      'sync_running': 'Inasawazisha...',
      'sync_completed': 'Usawazishaji umekamilika.',
      'sync_failed_short': 'Usawazishaji umeshindikana.',
      'offline_content_title': 'Data Nje ya Mtandao',
      'offline_content_desc':
          'Rekodi za nje ya mtandao husimamiwa kiotomatiki. Tumia "Sawazisha Sasa" kusukuma na kusasisha data.',
      'ok': 'Sawa',
      'about_app_desc':
          'Usimamizi wa shamba kwa mazao, wanyama, hesabu na mauzo.',
      'privacy_terms_title': 'Faragha na Masharti',
      'privacy_terms_desc':
          'Tumia data ya shamba iliyokubaliwa na linda ufikiaji wa kifaa. Sera kamili inapaswa kuunganishwa kabla ya uzinduzi.',
      'close_button': 'Funga',
      'edit_profile_title': 'Hariri Wasifu',
      'name_label': 'Jina',
      'location_label': 'Mahali',
      'profile_updated': 'Wasifu umesasishwa',
      'profile_update_failed': 'Imeshindwa kusasisha wasifu',
      'theme_system_default': 'Mfumo chaguomsingi',
      'theme_light': 'Mwanga',
      'theme_dark': 'Giza',
      'theme_updated_to': 'Mandhari imewekwa kuwa {theme}.',
      'apply': 'Tumia',
      'logged_out_successfully': 'Umetoka kwa mafanikio',
      'logout_failed': 'Kutoka kumeshindikana: {message}',
      'logout_confirm_title': 'Toka',
      'logout_confirm_body': 'Una uhakika unataka kutoka?',
      'profile_default_name': 'Mkulima',
      'help_support_title': 'Msaada',
      'help_email': 'Barua pepe: support@pamoja-twalima.app',
      'help_phone': 'Simu: +254 700 000 000',
      'help_response_time': 'Muda wa majibu: ndani ya saa 24',
      'version_label': 'Toleo {version}',
      'error_auth_invalid_credentials': 'Taarifa za kuingia si sahihi',
      'error_auth_login_failed': 'Kuingia kumeshindikana',
      'error_auth_invalid_email_password': 'Barua pepe au nenosiri si sahihi',
      'error_auth_too_many_attempts':
          'Majaribio mengi ya kuingia. Tafadhali jaribu tena baadaye.',
      'error_auth_invalid_registration': 'Taarifa za usajili si sahihi',
      'error_auth_registration_failed': 'Usajili umeshindikana',
      'error_profile_load': 'Imeshindwa kupakia wasifu',
      'error_profile_logout': 'Imeshindwa kutoka',
      'error_weather_load': 'Imeshindwa kupakia hali ya hewa',
      'error_knowledge_load_topics': 'Imeshindwa kupakia mada',
      'error_audit_load': 'Imeshindwa kupakia matukio ya ukaguzi',
      'error_marketplace_load': 'Imeshindwa kupakia bidhaa',
      'error_marketplace_add': 'Imeshindwa kuongeza bidhaa',
      'error_marketplace_update': 'Imeshindwa kusasisha bidhaa',
      'error_marketplace_delete': 'Imeshindwa kufuta bidhaa',
    },
  };

  String tr(String key) {
    final languageCode = locale.languageCode;
    final localizedMap =
        _localizedValues[languageCode] ?? _localizedValues['en']!;
    return localizedMap[key] ?? _localizedValues['en']![key] ?? key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'sw'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) {
    return false;
  }
}

extension AppLocalizationX on BuildContext {
  String tr(String key) => AppLocalizations.of(this).tr(key);
}
